In [14]:
#Lab Wine Quality
import pandas as pd
wine = pd.read_csv("wine.csv")
wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [ ]:

import pandas as pd
data = pd.read_csv("wine.csv")
y = data['quality']
x = data.drop(['quality'], axis=1)
#data.head()
c

Iteration 1, loss = 20.11451744
Iteration 2, loss = 10.84787675
Iteration 3, loss = 6.55556444
Iteration 4, loss = 4.62833060
Iteration 5, loss = 2.86952062
Iteration 6, loss = 2.16788956
Iteration 7, loss = 1.79510285
Iteration 8, loss = 1.50643080
Iteration 9, loss = 1.39582257
Iteration 10, loss = 1.33842867
Iteration 11, loss = 1.29943917
Iteration 12, loss = 1.28106199
Iteration 13, loss = 1.25934940
Iteration 14, loss = 1.24133964
Iteration 15, loss = 1.21429778
Iteration 16, loss = 1.20070078
Iteration 17, loss = 1.19438063
Iteration 18, loss = 1.18801833
Iteration 19, loss = 1.18131330
Iteration 20, loss = 1.17645959
Iteration 21, loss = 1.17349410
Iteration 22, loss = 1.16928084
Iteration 23, loss = 1.16661900
Iteration 24, loss = 1.16350493
Iteration 25, loss = 1.16099609
Iteration 26, loss = 1.16113508
Iteration 27, loss = 1.15983841
Iteration 28, loss = 1.15628321
Iteration 29, loss = 1.15961959
Iteration 30, loss = 1.16212186
Iteration 31, loss = 1.16084591
Iteration 32, loss = 1.15293470
Iteration 33, loss = 1.15206461
Iteration 34, loss = 1.15294806
Iteration 35, loss = 1.15280676
Iteration 36, loss = 1.15194013
Iteration 37, loss = 1.15119633
Iteration 38, loss = 1.14987819
Iteration 39, loss = 1.15092658
Iteration 40, loss = 1.15050208
Iteration 41, loss = 1.15034231
Iteration 42, loss = 1.14757689
Iteration 43, loss = 1.14900924
Iteration 44, loss = 1.14798820
Iteration 45, loss = 1.14627847
Iteration 46, loss = 1.14576680
Iteration 47, loss = 1.14601396
Iteration 48, loss = 1.14558137
Iteration 49, loss = 1.14592414
Iteration 50, loss = 1.14505554
Iteration 51, loss = 1.14625681
Iteration 52, loss = 1.14440277
Iteration 53, loss = 1.14402922
Iteration 54, loss = 1.14534875
Iteration 55, loss = 1.14605099
Iteration 56, loss = 1.14409791
Iteration 57, loss = 1.14251380
Iteration 58, loss = 1.14302310
Iteration 59, loss = 1.14161456
Iteration 60, loss = 1.14202694
Iteration 61, loss = 1.14052123
Iteration 62, loss = 1.14080888
Iteration 63, loss = 1.14069916
Iteration 64, loss = 1.14184895
Iteration 65, loss = 1.14213704
Iteration 66, loss = 1.14147484
Iteration 67, loss = 1.14237645
Iteration 68, loss = 1.14031323
Iteration 69, loss = 1.13931112
Iteration 70, loss = 1.14232011
Iteration 71, loss = 1.13877588
Iteration 72, loss = 1.13808194
Iteration 73, loss = 1.13911952
Iteration 74, loss = 1.13767894
Iteration 75, loss = 1.13781333
Iteration 76, loss = 1.13757823
Iteration 77, loss = 1.13737625
Iteration 78, loss = 1.13786548
Iteration 79, loss = 1.13783394
Iteration 80, loss = 1.13609206
Iteration 81, loss = 1.13538119
Iteration 82, loss = 1.13552689
Iteration 83, loss = 1.13752047
Iteration 84, loss = 1.13468495
Iteration 85, loss = 1.13541240
Iteration 86, loss = 1.13526720
Iteration 87, loss = 1.13354783
Iteration 88, loss = 1.13340645
Iteration 89, loss = 1.13444070
Iteration 90, loss = 1.13137634
Iteration 91, loss = 1.13275405
Iteration 92, loss = 1.13187228
Iteration 93, loss = 1.13037247
Iteration 94, loss = 1.13004000
Iteration 95, loss = 1.12949795
Iteration 96, loss = 1.12911366
Iteration 97, loss = 1.12855724
Iteration 98, loss = 1.12831859
Iteration 99, loss = 1.12738992
Iteration 100, loss = 1.12719872
Iteration 101, loss = 1.12575416
Iteration 102, loss = 1.12474778
Iteration 103, loss = 1.12566615
Iteration 104, loss = 1.12399353
Iteration 105, loss = 1.12472920
Iteration 106, loss = 1.12343470
Iteration 107, loss = 1.12191670
Iteration 108, loss = 1.12132115
Iteration 109, loss = 1.12129354
Iteration 110, loss = 1.11980132
Iteration 111, loss = 1.12223350
Iteration 112, loss = 1.11928403
Iteration 113, loss = 1.11764299
Iteration 114, loss = 1.11768712
Iteration 115, loss = 1.11532478
Iteration 116, loss = 1.11341110
Iteration 117, loss = 1.11339268
Iteration 118, loss = 1.11332025
Iteration 119, loss = 1.11207911
Iteration 120, loss = 1.11155279
Iteration 121, loss = 1.10966352
Iteration 122, loss = 1.10853799
Iteration 123, loss = 1.10753115
Iteration 124, loss = 1.10589877
Iteration 125, loss = 1.10505351
Iteration 126, loss = 1.10359671
Iteration 127, loss = 1.10558189
Iteration 128, loss = 1.10407111
Iteration 129, loss = 1.10430710
Iteration 130, loss = 1.10011135
Iteration 131, loss = 1.09973036
Iteration 132, loss = 1.10014874
Iteration 133, loss = 1.09838271
Iteration 134, loss = 1.09668373
Iteration 135, loss = 1.09395114
Iteration 136, loss = 1.09574021
Iteration 137, loss = 1.09388634
Iteration 138, loss = 1.09257037
Iteration 139, loss = 1.09085895
Iteration 140, loss = 1.08760340
Iteration 141, loss = 1.08587073
Iteration 142, loss = 1.08801970
Iteration 143, loss = 1.08258031
Iteration 144, loss = 1.08150916
Iteration 145, loss = 1.08315226
Iteration 146, loss = 1.08211100
Iteration 147, loss = 1.07909460
Iteration 148, loss = 1.08026291
Iteration 149, loss = 1.07662508
Iteration 150, loss = 1.07296057
Iteration 151, loss = 1.07724918
Iteration 152, loss = 1.07934455
Iteration 153, loss = 1.06623300
Iteration 154, loss = 1.06487284
Iteration 155, loss = 1.06127378
Iteration 156, loss = 1.05955289
Iteration 157, loss = 1.05763273
Iteration 158, loss = 1.05438460
Iteration 159, loss = 1.05311533
Iteration 160, loss = 1.05099224
Iteration 161, loss = 1.04817691
Iteration 162, loss = 1.05227432
Iteration 163, loss = 1.04300912
Iteration 164, loss = 1.03785505
Iteration 165, loss = 1.03480039
Iteration 166, loss = 1.03324731
Iteration 167, loss = 1.03049313
Iteration 168, loss = 1.03105245
Iteration 169, loss = 1.02674895
Iteration 170, loss = 1.02825711
Iteration 171, loss = 1.02065261
Iteration 172, loss = 1.02448759
Iteration 173, loss = 1.02279864
Iteration 174, loss = 1.01779651
Iteration 175, loss = 1.00905822
Iteration 176, loss = 1.00803013
Iteration 177, loss = 1.00482103
Iteration 178, loss = 1.00446962
Iteration 179, loss = 1.00073463
Iteration 180, loss = 0.99353495
Iteration 181, loss = 1.00023683
Iteration 182, loss = 1.00009074
Iteration 183, loss = 0.98737372
Iteration 184, loss = 0.98719295
Iteration 185, loss = 0.98273959
Iteration 186, loss = 0.98950083
Iteration 187, loss = 0.98297021
Iteration 188, loss = 0.97818115
Iteration 189, loss = 0.97842878
Iteration 190, loss = 0.98124960
Iteration 191, loss = 0.97345923
Iteration 192, loss = 0.97704058
Iteration 193, loss = 0.97077011
Iteration 194, loss = 0.97573120
Iteration 195, loss = 0.96763044
Iteration 196, loss = 0.97749613
Iteration 197, loss = 0.98556826
Iteration 198, loss = 0.98424960
Iteration 199, loss = 0.97688525
Iteration 200, loss = 0.97824722

c:\Users\HP\OneDrive\Documents\Internship\srm\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

MLPClassifier(hidden_layer_sizes=(6, 5), learning_rate_init=0.01,
              random_state=5, verbose=True)

In [25]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1199, 11)
(1199,)
(400, 11)
(400,)

In [26]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model = Sequential()
model.add(Dense(32, input_shape=(11), activation='relu'))
model.add(Dense(6, activation='softmax'))
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy', metrics=['accuracy'])
y_train = y_train-3
y_test = y_test-3
print(np.unique(y_train))

c:\Users\HP\OneDrive\Documents\Internship\srm\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

ValueError: Cannot convert '11' to a shape.

In [16]:
import tensorflow as tf
print(tf.__version__)

2.21.0

In [17]:
import pandas as pd
wine = pd.read_csv("wine.csv")
y=wine['quality']
x=wine.drop(['quality'],axis=1)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [18]:
from sklearn.neural_network import MLPClassifier
model=MLPClassifier(hidden_layer_sizes=(64,32),activation='tanh',max_iter=500)
model.fit(x_train,y_train)

print (model.score(x_test, y_test))

0.57

In [19]:
from sklearn.metrics import  confusion_matrix, classification_report
y_pred = model.predict(x_test)
confusion_matric= confusion_matrix(y_test, y_pred)
print(confusion_matric)

[[  0   0   1   0   0   0]
 [  0   0  10   3   0   0]
 [  0   1 135  27   1   0]
 [  0   0  79  82   8   0]
 [  0   0   5  32  11   0]
 [  0   0   0   4   1   0]]

In [29]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(64, input_dim=x_train.shape[1], activation='relu'))
model.add(Dense(6, activation='softmax'))
from tensorflow.keras.optimizers import Adam
model.compile(loss='sparse_categorical_crossentropy', optimizer=Adam(learning_rate=0.01), metrics=['accuracy'])



model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_11 (Dense)                │ (None, 64)             │           768 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 6)              │           390 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,158 (4.52 KB)

 Trainable params: 1,158 (4.52 KB)

 Non-trainable params: 0 (0.00 B)

In [30]:
print(x_train.shape)

(1199, 11)

In [31]:
print(model.predict(x_test))

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
[[1.3121088e-04 4.1108882e-01 8.0797513e-04 4.0712914e-01 4.1486219e-02
  1.3935654e-01]
 [2.6177140e-05 2.2093486e-02 6.4018715e-09 8.9313358e-01 1.1510296e-03
  8.3595641e-02]
 [1.0500410e-05 6.9473976e-01 3.0225167e-02 6.6737041e-02 1.2715214e-01
  8.1135377e-02]
 ...
 [3.9959501e-05 6.1203992e-01 1.9561943e-02 1.3451080e-01 6.4678438e-02
  1.6916893e-01]
 [4.1146643e-04 7.8908980e-01 5.4365922e-02 5.4652680e-02 4.8590343e-02
  5.2889813e-02]
 [7.0533664e-05 9.1943777e-01 2.3242503e-02 2.6183307e-02 2.0441636e-02
  1.0624256e-02]]

In [36]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model = Sequential()
model.add(Dense(32, input_shape=(11,), activation='relu'))
model.add(Dense(6, activation='softmax'))
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy', metrics=['accuracy'])
y_train = y_train-3
y_test = y_test-3
print(np.unique(y_train))

[-6 -5 -4 -3 -2 -1]

c:\Users\HP\OneDrive\Documents\Internship\srm\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [39]:
pred= model.predict(x_test)
pred= np.argmax(pred, axis=1)
pred= pred+3
print(pred)
model.save('wine_quality_model.h5')

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]

In [38]:
print(y_train)

582    -4
626    -4
1030   -2
620    -4
490    -3
       ..
1130   -3
1294   -3
860    -4
1459   -2
1126   -3
Name: quality, Length: 1199, dtype: int64

In [40]:
#House Rental Prediction
import pandas as pd 
bp=pd.read_csv("House_Rent_Dataset.csv")
bp.head()

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner

In [ ]:
#House Rental Prediction
import pandas as pd 
bp=pd.read_csv("House_Rent_Dataset.csv")
bp.head()

In [43]:

import pandas as pd
bp=pd.read_csv("House_Rent_Dataset.csv")
bp.head()
y=bp['Rent']
x=bp.drop(['Rent','Posted On','Floor','Area Locality'],axis=1)
import category_encoders as ce
encoder=ce.LeaveOneOutEncoder(return_df=True)
X = encoder.fit_transform(x,y)

In [45]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [46]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model = Sequential()
model.add(Dense(32, input_shape=(8,), activation='relu'))
model.add(Dense(1, activation='relu'))
model.compile(optimizer='adam',loss='mean_squared_error', metrics=['mae'])
model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.2)

Epoch 1/100

c:\Users\HP\OneDrive\Documents\Internship\srm\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

89/89 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7473076224.0000 - mae: 24048.7285 - val_loss: 3085659648.0000 - val_mae: 22996.6191
Epoch 2/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6861191680.0000 - mae: 25776.9160 - val_loss: 2942470656.0000 - val_mae: 22264.9004
Epoch 3/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6756201472.0000 - mae: 24027.8691 - val_loss: 2893619200.0000 - val_mae: 22808.9512
Epoch 4/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6712894464.0000 - mae: 23830.0352 - val_loss: 2871733504.0000 - val_mae: 22399.6855
Epoch 5/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6697199104.0000 - mae: 23441.2031 - val_loss: 2869248512.0000 - val_mae: 23277.1934
Epoch 6/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6669472256.0000 - mae: 24226.4707 - val_loss: 2846758912.0000 - val_mae: 20873.3613
Epoch 7/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6675429376.0000 - mae: 23528.3125 - val_loss: 2839166208.0000 - val_mae: 22552.5957
Epoch 8/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6660912640.0000 - mae: 23393.2148 - val_loss: 2833868800.0000 - val_mae: 22618.1973
Epoch 9/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6638298624.0000 - mae: 23656.0820 - val_loss: 2810511616.0000 - val_mae: 21139.4590
Epoch 10/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6641732608.0000 - mae: 22686.6172 - val_loss: 2810571264.0000 - val_mae: 22930.7168
Epoch 11/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6625202176.0000 - mae: 23421.8652 - val_loss: 2806511104.0000 - val_mae: 23239.7949
Epoch 12/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6623410688.0000 - mae: 23387.2246 - val_loss: 2774357248.0000 - val_mae: 20987.5840
Epoch 13/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6600031232.0000 - mae: 22875.2246 - val_loss: 2817394944.0000 - val_mae: 24366.6523
Epoch 14/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6594984448.0000 - mae: 23172.4121 - val_loss: 2802921984.0000 - val_mae: 24157.5312
Epoch 15/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6581628928.0000 - mae: 23204.0078 - val_loss: 2738764032.0000 - val_mae: 20795.1602
Epoch 16/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6570284544.0000 - mae: 22945.4297 - val_loss: 2727428352.0000 - val_mae: 20029.0664
Epoch 17/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6565920768.0000 - mae: 22725.6523 - val_loss: 2723486720.0000 - val_mae: 21518.3379
Epoch 18/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6556750336.0000 - mae: 22869.8496 - val_loss: 2731157248.0000 - val_mae: 22814.8320
Epoch 19/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6542990336.0000 - mae: 22367.8301 - val_loss: 2721465344.0000 - val_mae: 22716.6895
Epoch 20/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6531654144.0000 - mae: 22282.2852 - val_loss: 2683037184.0000 - val_mae: 21707.9180
Epoch 21/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6527589888.0000 - mae: 23243.5254 - val_loss: 2668685056.0000 - val_mae: 21141.6133
Epoch 22/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6535632896.0000 - mae: 22330.2578 - val_loss: 2659689984.0000 - val_mae: 21163.3301
Epoch 23/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6505117184.0000 - mae: 22535.0293 - val_loss: 2636579072.0000 - val_mae: 20312.6328
Epoch 24/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6476675584.0000 - mae: 22107.8027 - val_loss: 2639967488.0000 - val_mae: 21912.6992
Epoch 25/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6466700288.0000 - mae: 22369.0195 - val_loss: 2603673600.0000 - val_mae: 19816.1914
Epoch 26/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6465414144.0000 - mae: 21928.0449 - val_loss: 2608158720.0000 - val_mae: 21695.6270
Epoch 27/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6439977984.0000 - mae: 22273.5684 - val_loss: 2576125696.0000 - val_mae: 20136.1426
Epoch 28/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6430103552.0000 - mae: 22084.0195 - val_loss: 2560066304.0000 - val_mae: 19283.6289
Epoch 29/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6431664128.0000 - mae: 21674.0742 - val_loss: 2552936448.0000 - val_mae: 19978.2266
Epoch 30/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6416972800.0000 - mae: 21743.9961 - val_loss: 2554774784.0000 - val_mae: 21159.2324
Epoch 31/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6396450816.0000 - mae: 21617.4824 - val_loss: 2612270080.0000 - val_mae: 24140.4492
Epoch 32/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6391314944.0000 - mae: 21714.3496 - val_loss: 2547665920.0000 - val_mae: 22092.9023
Epoch 33/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6377531392.0000 - mae: 22179.8281 - val_loss: 2529018112.0000 - val_mae: 21660.0000
Epoch 34/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6352609792.0000 - mae: 21328.2031 - val_loss: 2508216064.0000 - val_mae: 21488.5352
Epoch 35/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6346772992.0000 - mae: 21074.2852 - val_loss: 2706046720.0000 - val_mae: 27591.8711
Epoch 36/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6386527744.0000 - mae: 22259.4199 - val_loss: 2478576640.0000 - val_mae: 20946.3672
Epoch 37/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6309237760.0000 - mae: 21463.2051 - val_loss: 2498887936.0000 - val_mae: 22570.6035
Epoch 38/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6310306304.0000 - mae: 21550.3359 - val_loss: 2428958208.0000 - val_mae: 19505.0605
Epoch 39/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 6296451584.0000 - mae: 21276.7656 - val_loss: 2420681984.0000 - val_mae: 18464.6094
Epoch 40/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 6272002560.0000 - mae: 21238.1113 - val_loss: 2396367104.0000 - val_mae: 19245.8066
Epoch 41/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - loss: 6251502080.0000 - mae: 20417.9902 - val_loss: 2451092480.0000 - val_mae: 22662.2754
Epoch 42/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 6255655424.0000 - mae: 22140.7891 - val_loss: 2383924480.0000 - val_mae: 20524.3926
Epoch 43/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - loss: 6232083968.0000 - mae: 20999.3535 - val_loss: 2362131456.0000 - val_mae: 19804.8125
Epoch 44/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - loss: 6217599488.0000 - mae: 20803.2383 - val_loss: 2341352448.0000 - val_mae: 19631.6133
Epoch 45/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - loss: 6207314944.0000 - mae: 20821.8359 - val_loss: 2326338560.0000 - val_mae: 19567.0293
Epoch 46/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 6s 32ms/step - loss: 6191089664.0000 - mae: 20663.8008 - val_loss: 2322126848.0000 - val_mae: 20128.7910
Epoch 47/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - loss: 6172444160.0000 - mae: 20255.4824 - val_loss: 2303649280.0000 - val_mae: 19989.4004
Epoch 48/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 3s 27ms/step - loss: 6160108544.0000 - mae: 21346.9473 - val_loss: 2284582656.0000 - val_mae: 18138.2871
Epoch 49/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - loss: 6177896960.0000 - mae: 20832.2520 - val_loss: 2292425472.0000 - val_mae: 20727.3223
Epoch 50/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 5s 50ms/step - loss: 6129057280.0000 - mae: 20712.8027 - val_loss: 2331349504.0000 - val_mae: 22526.9727
Epoch 51/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 6126067712.0000 - mae: 20178.8750 - val_loss: 2338511616.0000 - val_mae: 23406.4707
Epoch 52/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - loss: 6118347264.0000 - mae: 21098.1660 - val_loss: 2235770112.0000 - val_mae: 19804.2031
Epoch 53/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 6087400448.0000 - mae: 20543.8027 - val_loss: 2208570112.0000 - val_mae: 18942.9551
Epoch 54/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - loss: 6070913536.0000 - mae: 20775.5391 - val_loss: 2203206656.0000 - val_mae: 17939.1016
Epoch 55/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - loss: 6066789888.0000 - mae: 20589.9336 - val_loss: 2179434752.0000 - val_mae: 18107.3496
Epoch 56/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6052187136.0000 - mae: 20610.0801 - val_loss: 2182191104.0000 - val_mae: 17795.1973
Epoch 57/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6034704896.0000 - mae: 20432.4219 - val_loss: 2165886464.0000 - val_mae: 17622.9629
Epoch 58/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6024575488.0000 - mae: 19906.3984 - val_loss: 2199853568.0000 - val_mae: 21731.9102
Epoch 59/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6008821248.0000 - mae: 20717.6250 - val_loss: 2173131264.0000 - val_mae: 21141.1094
Epoch 60/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5979177984.0000 - mae: 20673.1836 - val_loss: 2114233856.0000 - val_mae: 18600.5332
Epoch 61/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5987886080.0000 - mae: 20365.1777 - val_loss: 2096081024.0000 - val_mae: 18310.2734
Epoch 62/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5982011392.0000 - mae: 20090.0352 - val_loss: 2097813248.0000 - val_mae: 19616.7793
Epoch 63/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5973185024.0000 - mae: 20472.4980 - val_loss: 2076359552.0000 - val_mae: 19001.4922
Epoch 64/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5938018304.0000 - mae: 19877.8203 - val_loss: 2054214016.0000 - val_mae: 18236.0684
Epoch 65/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5943823360.0000 - mae: 20274.2129 - val_loss: 2076224256.0000 - val_mae: 19875.3535
Epoch 66/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5926773248.0000 - mae: 20460.0918 - val_loss: 2036314496.0000 - val_mae: 18395.6172
Epoch 67/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5904314368.0000 - mae: 20298.8906 - val_loss: 2026453888.0000 - val_mae: 18714.0469
Epoch 68/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5901013504.0000 - mae: 20128.8438 - val_loss: 2013099648.0000 - val_mae: 17766.8984
Epoch 69/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5896027136.0000 - mae: 20081.5273 - val_loss: 2005120000.0000 - val_mae: 18047.2500
Epoch 70/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5883122176.0000 - mae: 20372.8984 - val_loss: 2043333504.0000 - val_mae: 20930.3906
Epoch 71/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5877269504.0000 - mae: 20219.7852 - val_loss: 1991700096.0000 - val_mae: 19035.9219
Epoch 72/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5859995136.0000 - mae: 20078.5762 - val_loss: 1975230592.0000 - val_mae: 19099.5273
Epoch 73/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5835963904.0000 - mae: 20137.4238 - val_loss: 1954658688.0000 - val_mae: 18108.0996
Epoch 74/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5825568768.0000 - mae: 20036.0762 - val_loss: 2049774464.0000 - val_mae: 22166.7637
Epoch 75/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5837196800.0000 - mae: 19958.3105 - val_loss: 2028893824.0000 - val_mae: 21840.5938
Epoch 76/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5813656576.0000 - mae: 20501.6367 - val_loss: 1925656576.0000 - val_mae: 18526.1582
Epoch 77/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5796422656.0000 - mae: 20111.1465 - val_loss: 1924004736.0000 - val_mae: 17897.7461
Epoch 78/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5798473728.0000 - mae: 20045.2324 - val_loss: 1915352576.0000 - val_mae: 18026.3262
Epoch 79/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5774987776.0000 - mae: 20046.7070 - val_loss: 1894922624.0000 - val_mae: 18784.3203
Epoch 80/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5758389248.0000 - mae: 20207.5137 - val_loss: 1887922432.0000 - val_mae: 17815.3281
Epoch 81/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5756153344.0000 - mae: 19548.5566 - val_loss: 1890093184.0000 - val_mae: 19591.0215
Epoch 82/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5759044608.0000 - mae: 20445.7188 - val_loss: 1888570240.0000 - val_mae: 19651.1562
Epoch 83/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5727353344.0000 - mae: 19985.3105 - val_loss: 1861602944.0000 - val_mae: 18906.0684
Epoch 84/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5724987904.0000 - mae: 19829.0684 - val_loss: 1852609024.0000 - val_mae: 18395.4336
Epoch 85/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5706688512.0000 - mae: 19909.5820 - val_loss: 1855234688.0000 - val_mae: 19342.3828
Epoch 86/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5707818496.0000 - mae: 19855.8789 - val_loss: 1844856832.0000 - val_mae: 19150.2129
Epoch 87/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5724422656.0000 - mae: 20020.4121 - val_loss: 1894894464.0000 - val_mae: 21096.7383
Epoch 88/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5677166080.0000 - mae: 20088.5488 - val_loss: 1811734016.0000 - val_mae: 17786.0781
Epoch 89/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5694801408.0000 - mae: 20106.2539 - val_loss: 1803927552.0000 - val_mae: 18541.3516
Epoch 90/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5666576384.0000 - mae: 19795.7305 - val_loss: 1799718528.0000 - val_mae: 17807.8164
Epoch 91/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - loss: 5664974336.0000 - mae: 20086.6484 - val_loss: 1787707008.0000 - val_mae: 18368.5176
Epoch 92/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - loss: 5651483136.0000 - mae: 19794.7285 - val_loss: 1788835456.0000 - val_mae: 18066.5410
Epoch 93/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 5645296128.0000 - mae: 20291.5254 - val_loss: 1776605440.0000 - val_mae: 18751.2441
Epoch 94/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 5654961664.0000 - mae: 20455.2969 - val_loss: 1760420352.0000 - val_mae: 18263.9668
Epoch 95/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 5636746240.0000 - mae: 19985.6152 - val_loss: 1762128256.0000 - val_mae: 18741.5684
Epoch 96/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 5641006080.0000 - mae: 20328.7676 - val_loss: 1753214336.0000 - val_mae: 18297.8809
Epoch 97/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 3s 27ms/step - loss: 5607077376.0000 - mae: 19962.3457 - val_loss: 1752960000.0000 - val_mae: 17724.8613
Epoch 98/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 3s 27ms/step - loss: 5628520960.0000 - mae: 19966.3262 - val_loss: 1774472832.0000 - val_mae: 17610.1172
Epoch 99/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - loss: 5622725120.0000 - mae: 20155.3906 - val_loss: 1757922432.0000 - val_mae: 19555.0195
Epoch 100/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - loss: 5598718976.0000 - mae: 19961.5801 - val_loss: 1722454016.0000 - val_mae: 18439.0664

In [ ]:
from tensorflow.keras.layers import Dense